# Site
repository: M-Razavi/Resume
# favicon: images/favicon.ico

# Personal info
name: Mahdi Razavi
title: Software Enginieer
email: Razavi.Dev@Gmail.com
phone: +989133362873
website: Mahdi.Razavi.net

# Social links
# twitter_username: facespics
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
github_username:  m-razavi
linkedin_username: mahdirazavi
xing_username: mahdi_razavi

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>
  Software Engineer with 7 years in software development based on the platforms Windows and Linux and expertise in development and operations. 
  Expert in object-oriented design and analysis through intuitive problem-solving and creativity. 
  Successfully maintains professionalism and personal commitment with excellent communication and people skills with the ability to train, motivate and supervise a team. 

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
